const ERROR_INVALID_EMAIL = 'ERROR_INVALID_EMAIL';

const ERROR_WRONG_PASSWORD = 'ERROR_WRONG_PASSWORD';

const ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND';

const ERROR_USER_DISABLED = 'ERROR_USER_DISABLED';

const ERROR_TOO_MANY_REQUESTS = 'ERROR_TOO_MANY_REQUESTS';

const ERROR_OPERATION_NOT_ALLOWED = 'ERROR_OPERATION_NOT_ALLOWED';

const ERROR_NETWORK_REQUEST_FAILED = 'ERROR_NETWORK_REQUEST_FAILED';

const ERROR_EMAIL_ALREADY_IN_USE = 'ERROR_EMAIL_ALREADY_IN_USE';
